[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.7"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.7"

[prune]
  go-tests = true
  unused-packages = true
